/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifpb.visao;

import br.com.ifpb.Proxy.ControladorProxy;
import br.com.ifpb.huffman.Controlador;
import br.com.ifpb.models.Grafico;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gilvonaldo
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private File arquivoSelecionado = null;
    private Controlador controle = new Controlador();
    private File destino;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jBtDiretorios = new javax.swing.JButton();
        jTextURL = new javax.swing.JTextField();
        jBtCompactar = new javax.swing.JButton();
        jBtDescompactar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jBtDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtDiretorios.setText("Arquivo");
        jBtDiretorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDiretoriosActionPerformed(evt);
            }
        });

        jBtCompactar.setText("Compactar");
        jBtCompactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCompactarActionPerformed(evt);
            }
        });

        jBtDescompactar.setText("Descompactar");
        jBtDescompactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDescompactarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        jLabel1.setText("IFZip");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButton1.setText("ZIP");

        jRadioButton2.setText("RAR");

        jRadioButton3.setText("MAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jBtDetalhes.setText("Detalhes");
        jBtDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jBtDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtDescompactar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtCompactar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtDiretorios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtDiretorios))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtCompactar)
                            .addComponent(jBtDescompactar)
                            .addComponent(jBtDetalhes))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtDiretoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDiretoriosActionPerformed

        JFileChooser chooserArquivo = new JFileChooser();

        int escolha = chooserArquivo.showOpenDialog(getParent());
        chooserArquivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File arq = chooserArquivo.getSelectedFile();
        this.arquivoSelecionado = arq;
        jTextURL.setText(arquivoSelecionado.getAbsolutePath());

    }//GEN-LAST:event_jBtDiretoriosActionPerformed

    private void jBtCompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCompactarActionPerformed
        JFileChooser fc = new JFileChooser();

        File diretorio = null;

        // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            diretorio = fc.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Voce escolheu o diretório: " + diretorio.getName());
        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum diretorio.");
        }

        ControladorProxy proxy = new ControladorProxy();

        proxy.compactar(this.arquivoSelecionado, diretorio);

    }//GEN-LAST:event_jBtCompactarActionPerformed

    private void jBtDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDetalhesActionPerformed

        ArrayList a = new ArrayList();
        ArrayList b = new ArrayList();
        a.add("A");
        a.add("B");
        a.add("C");
        a.add("D");
        a.add("E");
        a.add("F");
        a.add("G");
        a.add("H");
        a.add("I");
        a.add("J");
        
        
        
        b.add(19);
        b.add(45);
        b.add(27);
        b.add(39);
        b.add(12);
        b.add(27);
        b.add(11);
        b.add(12);
        b.add(40);
        b.add(69);
        

        JFrame frame = new JFrame();
        frame.add(Grafico.pizza3DStatic(a, b, "Palavras Frequentes"));
        frame.setVisible(true);
        
        frame.setSize(400, 250);

        frame.setLocationRelativeTo(null);
        controle.gerarGrafico(arquivoSelecionado.getAbsolutePath());

    }//GEN-LAST:event_jBtDetalhesActionPerformed

    private void jBtDescompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDescompactarActionPerformed

        JFileChooser chooserArquivo = new JFileChooser();
        chooserArquivo.setCurrentDirectory(new java.io.File("."));
        int escolha = chooserArquivo.showOpenDialog(getParent());
        chooserArquivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        chooserArquivo.setAcceptAllFileFilterUsed(false);

        File arq = chooserArquivo.getCurrentDirectory();

        ControladorProxy proxy = new ControladorProxy();

        try {
            controle.descompactar(arq, arq);

        } catch (IOException ex) {
            Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtDescompactarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtCompactar;
    private javax.swing.JButton jBtDescompactar;
    private javax.swing.JButton jBtDetalhes;
    private javax.swing.JButton jBtDiretorios;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextURL;
    // End of variables declaration//GEN-END:variables
}
